#ifndef CTRLDEF
#define CTRLDEF

#define NCURSES_PAGE_LACATION_EXPLAIN_Y 13

#define NCURSES_PAGE_LACATION_STAR_X 24

#define NCURSES_PAGE_LACATION_TITLE_X 30
#define NCURSES_PAGE_LACATION_TITLE_Y 1


#define NCURSES_PAGE_LACATION_BORDER_X0 22
#define NCURSES_PAGE_LACATION_BORDER_X1 (44+NCURSES_PAGE_LACATION_BORDER_X0)
#define NCURSES_PAGE_LACATION_BORDER_Y0 0
#define NCURSES_PAGE_LACATION_BORDER_Y1 12

#endif

